export const PROPERTY = 'property';
export const ID = 'id';
export const TIME = 'time';

//ACTIONS
export const LOAD_ALL_APPOINTMENTS = "LOAD_ALL_APPOINTMENTS";
export const LOAD_APPOINTMENTS_SUCCESS = "LOAD_APPOINTMENTS_SUCCESS";
export const CREATE_APPOINTMENT = "CREATE_APPOINTMENT";
export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS";